// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fabrizio.DAL;

#nullable disable

namespace fabrizio.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205130421_Destination")]
    partial class Destination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fabrizio.DAL.Entities.AccommodationBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TripId");

                    b.ToTable("AccommodationBookings", (string)null);
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100000L);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TripId");

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.TravelBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TripId");

                    b.ToTable("TravelBookings", (string)null);
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.AccommodationBooking", b =>
                {
                    b.HasOne("fabrizio.DAL.Entities.Account", "Account")
                        .WithMany("AccommodationBookings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fabrizio.DAL.Entities.Trip", "Trip")
                        .WithMany("AccommodationBookings")
                        .HasForeignKey("TripId");

                    b.OwnsOne("fabrizio.DAL.Entities.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AccommodationBookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AddTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("EditTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("AccommodationBookingId");

                            b1.ToTable("AccommodationBookings");

                            b1.WithOwner()
                                .HasForeignKey("AccommodationBookingId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.Account", b =>
                {
                    b.OwnsOne("fabrizio.DAL.Entities.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("AddTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("EditTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.Destination", b =>
                {
                    b.HasOne("fabrizio.DAL.Entities.Account", "Account")
                        .WithMany("Destinations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fabrizio.DAL.Entities.Trip", "Trip")
                        .WithMany("Destinations")
                        .HasForeignKey("TripId");

                    b.OwnsOne("fabrizio.DAL.Entities.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("DestinationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AddTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("EditTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("DestinationId");

                            b1.ToTable("Destinations");

                            b1.WithOwner()
                                .HasForeignKey("DestinationId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.TravelBooking", b =>
                {
                    b.HasOne("fabrizio.DAL.Entities.Account", "Account")
                        .WithMany("TravelBookings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fabrizio.DAL.Entities.Trip", "Trip")
                        .WithMany("TravelBookings")
                        .HasForeignKey("TripId");

                    b.OwnsOne("fabrizio.DAL.Entities.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TravelBookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AddTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("EditTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("TravelBookingId");

                            b1.ToTable("TravelBookings");

                            b1.WithOwner()
                                .HasForeignKey("TravelBookingId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.Trip", b =>
                {
                    b.HasOne("fabrizio.DAL.Entities.Account", "Account")
                        .WithMany("Trips")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("fabrizio.DAL.Entities.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AddTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("EditTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.Account", b =>
                {
                    b.Navigation("AccommodationBookings");

                    b.Navigation("Destinations");

                    b.Navigation("TravelBookings");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("fabrizio.DAL.Entities.Trip", b =>
                {
                    b.Navigation("AccommodationBookings");

                    b.Navigation("Destinations");

                    b.Navigation("TravelBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
